### ISSUE TITLE
Add support for Digits Authentication

### ISSUE THREAD

**Issue by kdawgwilk** [stormpath/Turnstile#14]
[Digits by Twitter Fabric](https://get.digits.com) is similar to [Account Kit by Facebook](https://developers.facebook.com/docs/accountkit) 

A few relevant URLs showing how it works:

[How can I verify DGTSession tokens on my own server](https://twittercommunity.com/t/digits-how-can-i-verify-dgtsession-tokens-on-my-own-server/26036)
[Advanced Setup - Verifying a User](https://docs.fabric.io/apple/digits/advanced-setup.html#verifying-a-user)

It uses a technique called [OAuth Echo (explained here)](https://dev.twitter.com/oauth/echo)

**Comment by edjiang** [comment]
Fixed in #19
