### ISSUE TITLE
Update to Swift 8-15

### ISSUE THREAD

**Issue by edjiang** [stormpath/Turnstile#2]
Blocked on vapor/engine, vapor/json, and SecretSocks. @tannernelson, I'm doing other work this week -- can you ping me when the vapor dependencies are ready? If SecretSocks needs work I can take a look into it.

**Comment by edjiang** [comment]
Task list right now: I'm checking off ones with active PRs
- [ ] Engine https://github.com/vapor/engine
  - [ ] SHA1 https://github.com/CryptoKitten/SHA1
    - [ ] CryptoEssentials https://github.com/CryptoKitten/CryptoEssentials
  - [x] Socks https://github.com/czechboy0/Socks
  - [x] Core https://github.com/vapor/core
    - [x] Strand https://github.com/ketzusaka/Strand
- [x] SecretSocks https://github.com/czechboy0/SecretSocks
  - [x] Socks https://github.com/czechboy0/Socks
  - [x] TLS https://github.com/qutheory/tls
    - [x] COpenSSL https://github.com/Zewo/COpenSSL@0.6.2>

**Comment by edjiang** [comment]
@tannernelson btw I think I'm going to use JSONSerialization for the next release (since it seems to be OK on linux now?), so no worries about updating that.

**Comment by tanner0101** [comment]
vapor/JSON is just a wrapper around Foundation's JSON. Core should be good with version 0.5 and Joannis is working on making our crypto lib 8-18 compatible.
