### ISSUE TITLE
typo in Credentials.swift

### ISSUE THREAD

**Issue by xGoPox** [stormpath/Turnstile#25]
there is a typo at Sesssion with 3 's' :
`public struct Sesssion: Credentials {}`
should be :
`public struct Session: Credentials {}`

**Comment by edjiang** [comment]
Oh shoot, well this is embarrassing! =D Thanks for noticing! Can't go around breaking people's code, so this will probably stay for the near future -- although I'll work on deprecating it and removing it for 2.0

**Comment by kdawgwilk** [comment]
Maybe renaming it and including a typealias for backward compatibility till version 2 hits?

**Comment by edjiang** [comment]
Yep! It's been a while. Need to catch up on all of this Turnstile stuff. Should have time in ~2 weeks or so!

**Comment by edjiang** [comment]
Fixed in #29
