### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by nikitabelopotapov** [stormpath/Turnstile#32]
How can i implement my own class inheriting Credentials?
Always gets UnsupportedCredentialsError with login/register methods

I tried to inherit from UsernamePassword - that worked, but i had to make some changes in this class.

is there any good way implementing own Credentials?

**Comment by edjiang** [comment]
Yeah, you can implement your own credentials -- it's just that the pre-implemented `Realm`s don't support custom credentials. You'll need to write a Realm that supports you credentials using these instructions:

https://github.com/stormpath/Turnstile#realm
